# Generated by Django 6.0.2 on 2026-02-09 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('study_type', models.CharField(choices=[('CXR', 'Chest X-Ray'), ('MRI', 'Brain MRI')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ai_results', models.JSONField(blank=True, null=True)),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='heatmaps/%Y/%m/%d/')),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
