# Generated by Django 4.2.30 on 2026-04-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('image', models.ImageField(upload_to='studies/')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('heatmap_url', models.URLField(blank=True, null=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='studies.study')),
            ],
        ),
    ]
