# Generated by Django 4.2.30 on 2026-05-06 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='study',
            name='image',
            field=models.FileField(upload_to='studies/'),
        ),
        migrations.AlterField(
            model_name='study',
            name='modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
